version: "2"
services:

  postgres:
    image: postgres:9.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT
    volumes:
      - ./volumes:/shared
    ports:
      - "${LOCAL_POSTGRES_PORT}:5432"

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper

  overlord:
    image: nvhoang/druid:0.9.1.1
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - overlord
    volumes:
      - ./volumes:/shared
    ports:
      - "${LOCAL_OVERLORD_PORT}:8090"

  coordinator:
    image: nvhoang/druid:0.9.1.1
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - coordinator
    ports:
      - "${LOCAL_COORDINATOR_PORT}:8081"
    volumes:
      - ./volumes:/shared

  middlemanager:
    image: nvhoang/druid:0.9.1.1
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - middleManager
    volumes:
      - ./volumes:/shared

  historical:
    image: nvhoang/druid:0.9.1.1
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - historical
    volumes:
      - ./volumes:/shared

  broker:
    image: nvhoang/druid:0.9.1.1
    environment:
      - DRUID_XMX=1g 
      - DRUID_XMS=1g 
      - DRUID_MAXNEWSIZE=250m 
      - DRUID_NEWSIZE=250m
    command:
      - broker
    volumes:
      - ./volumes:/shared
    ports:
      - "${LOCAL_BROKER_PORT}:8082"


